plugins {
  id 'org.owasp.dependencycheck' version '12.2.2'
  id 'scala'
  id 'java-library'
  id 'io.gatling.gradle' version '3.15.0'
}

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

dependencies {
  gatlingImplementation project(":common-performance")
}

tasks.withType(Copy).all{
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

repositories {
  mavenCentral()
}

gatling {
  gatlingVersion '3.15.0'
  scalaVersion '2.13.11'
}

sourceSets {
  gatling {
    scala {
      srcDir 'src/gatling/simulations'
    }
    resources {
      srcDir 'src/gatling/resources'
    }
  }
}